"""first revision

Revision ID: 8bc06c47c69a
Revises: e088881e0697
Create Date: 2021-04-05 21:20:08.999563

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bc06c47c69a"
down_revision = "e088881e0697"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pecha", sa.Column("collection_title", sa.String(), nullable=True))
    op.add_column("pecha", sa.Column("publisher", sa.String(), nullable=True))
    op.add_column("pecha", sa.Column("source_id", sa.String(), nullable=True))
    op.add_column("pecha", sa.Column("subtitle", sa.String(), nullable=True))
    op.add_column("pecha", sa.Column("volume", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_pecha_collection_title"), "pecha", ["collection_title"], unique=False
    )
    op.create_index(op.f("ix_pecha_publisher"), "pecha", ["publisher"], unique=False)
    op.create_index(op.f("ix_pecha_source_id"), "pecha", ["source_id"], unique=False)
    op.create_index(op.f("ix_pecha_subtitle"), "pecha", ["subtitle"], unique=False)
    op.create_index(op.f("ix_pecha_volume"), "pecha", ["volume"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pecha_volume"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_subtitle"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_source_id"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_publisher"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_collection_title"), table_name="pecha")
    op.drop_column("pecha", "volume")
    op.drop_column("pecha", "subtitle")
    op.drop_column("pecha", "source_id")
    op.drop_column("pecha", "publisher")
    op.drop_column("pecha", "collection_title")
    # ### end Alembic commands ###
