"""change pecha id type to string

Revision ID: de61e3c0cead
Revises: 5fd95efc31eb
Create Date: 2021-04-08 12:50:50.546995

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "de61e3c0cead"
down_revision = "5fd95efc31eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pecha",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_index("ix_pecha_author", table_name="pecha")
    op.drop_index("ix_pecha_collection_title", table_name="pecha")
    op.drop_index("ix_pecha_publisher", table_name="pecha")
    op.drop_index("ix_pecha_source_id", table_name="pecha")
    op.drop_index("ix_pecha_subtitle", table_name="pecha")
    op.drop_index("ix_pecha_volume", table_name="pecha")
    op.drop_column("pecha", "collection_title")
    op.drop_column("pecha", "subtitle")
    op.drop_column("pecha", "publisher")
    op.drop_column("pecha", "volume")
    op.drop_column("pecha", "author")
    op.drop_column("pecha", "source_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pecha",
        sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pecha", sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pecha", sa.Column("volume", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pecha",
        sa.Column("publisher", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "pecha", sa.Column("subtitle", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "pecha",
        sa.Column("collection_title", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index("ix_pecha_volume", "pecha", ["volume"], unique=False)
    op.create_index("ix_pecha_subtitle", "pecha", ["subtitle"], unique=False)
    op.create_index("ix_pecha_source_id", "pecha", ["source_id"], unique=False)
    op.create_index("ix_pecha_publisher", "pecha", ["publisher"], unique=False)
    op.create_index(
        "ix_pecha_collection_title", "pecha", ["collection_title"], unique=False
    )
    op.create_index("ix_pecha_author", "pecha", ["author"], unique=False)
    op.alter_column(
        "pecha",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
