"""first revision

Revision ID: e088881e0697
Revises:
Create Date: 2021-04-02 00:20:56.560640

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e088881e0697"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "pecha",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pecha_author"), "pecha", ["author"], unique=False)
    op.create_index(op.f("ix_pecha_id"), "pecha", ["id"], unique=False)
    op.create_index(op.f("ix_pecha_title"), "pecha", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pecha_title"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_id"), table_name="pecha")
    op.drop_index(op.f("ix_pecha_author"), table_name="pecha")
    op.drop_table("pecha")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
