"""make user email nullable

Revision ID: d139896a84a2
Revises: 1b17b71a69bc
Create Date: 2021-04-22 09:42:19.665534

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d139896a84a2"
down_revision = "1b17b71a69bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index("ix_user_email", table_name="user")
    op.create_unique_constraint(None, "user", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
