name: CI/CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Create dummy .env
        run: |
          touch .env
          echo 'GITHUB_OAUTH_CLIENT_ID="xxx"' >> .env
          echo 'GITHUB_OAUTH_CLIENT_SECRET="xxx"' >> .env
          echo 'BACKEND_CORS_ORIGINS=["http://localhost"]' >> .env
      - name: Run Test
        run: pytest app/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd openpecha-services
            cd openpecha-api
            git pull origin main
            cd ..
            docker-compose up -d --build api-service
            
    
    
   
