name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
      
  build:
#     needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - 
      name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - 
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push openpecha-api image
      id: docker_build_api
      uses: docker/build-push-action@v2
      with:
        context: .
        file: api.dockerfile
        push: true
        tags: openpecha/openpecha-api:prod-${{ env.GIT_SHA }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    - 
      name: Build and push celery worker image
      id: docker_build_worker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: celeryworker.dockerfile
        push: true
        tags: openpecha/celeryworker-api:prod-${{ env.GIT_SHA }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    -
      name: Image digest
      run: |
        echo ${{ steps.docker_build_api.outputs.digest }}
        echo ${{ steps.docker_build_worker.outputs.digest }}
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Environment Variables
        run: |
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - 
        uses: appleboy/ssh-action@master
        env:
          SHA: ${{ env.GIT_SHA }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: SHA
          script_stop: true
          script: |
            docker service update --image openpecha/openpecha-api:prod-${SHA} openpecha-org_api
            docker service update --image openpecha/celeryworker-api:prod-${SHA} openpecha-org_celeryworker
            docker system prune -af --volumes
