name: CI/CD

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: '3.8'
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#           pip install pytest
#       - name: Create dummy .env
#         run: |
#           touch .env
#           echo 'GITHUB_OAUTH_CLIENT_ID="xxx"' >> .env
#           echo 'GITHUB_OAUTH_CLIENT_SECRET="xxx"' >> .env
#           echo 'GITHUB_TOKEN="xxx"' >> .env
#           echo 'BACKEND_CORS_ORIGINS=["http://localhost"]' >> .env
#       - name: Run Test
#         run: pytest app/

  build:
#     needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: openpecha/openpecha-api
        dockerfile: api.dockerfile
        tags: prod
            
    
    
   
